# Generated by Django 4.1.5 on 2023-02-02 17:31

from django.db import migrations, models
import django_jsonfield_backport.models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
                ('limit_timescale', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('limit', models.IntegerField()),
                ('limit_timescale', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', unixtimestampfield.fields.UnixTimeStampField(default=0.0, null=True)),
                ('activities', django_jsonfield_backport.models.JSONField()),
                ('times', django_jsonfield_backport.models.JSONField()),
                ('counts', django_jsonfield_backport.models.JSONField()),
                ('scales', django_jsonfield_backport.models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', unixtimestampfield.fields.UnixTimeStampField(default=0.0, null=True)),
                ('description', models.CharField(max_length=1024)),
                ('desired_end_date', unixtimestampfield.fields.UnixTimeStampField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', unixtimestampfield.fields.UnixTimeStampField(default=0.0, null=True)),
                ('page_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_pk', models.IntegerField()),
                ('created_at', unixtimestampfield.fields.UnixTimeStampField(default=0.0, null=True)),
                ('content', models.CharField(max_length=16392)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', unixtimestampfield.fields.UnixTimeStampField(default=0.0, null=True)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('minimum', unixtimestampfield.fields.UnixTimeStampField(default=0.0, null=True)),
                ('maximum', unixtimestampfield.fields.UnixTimeStampField(default=0.0, null=True)),
                ('description', models.CharField(max_length=512)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
