# Generated by Django 4.1.5 on 2023-02-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='maximum',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='minimum',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='time',
            name='maximum',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='time',
            name='minimum',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
