# Generated by Django 4.1.5 on 2023-02-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_day_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='primary_color',
            field=models.CharField(default='#fcfcfc', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='secondary_color',
            field=models.CharField(default='#fcfcfc', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
