# Generated by Django 4.1.5 on 2023-02-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_activity_primary_color_activity_secondary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_positive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
