# Generated by Django 4.1.5 on 2023-02-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_activity_is_positive_alter_activity_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='is_positive',
            new_name='positive',
        ),
    ]
